print("|============= Welcome to College Equiry Chatbot System! =============|")
print("|============================== Feel Free ============================|")
print("|================================== To ===============================|")
print("|=============== Ask your any query about our college ================|")
message = input(" / you:")
if message == "hi":
    print("hi,your good name")
    message = input(" / you:")
    print((" hi,raji "))
    
    print(("how can i help you?"))
    message = input("/ you:")
    print( "no iam not a robot")
    message = input ("/ you:")
    print("what do you know about")
    message = input (" / you:")
    print("which type of courses do you want to know")
    print("either Arts or Science")
    message = input("/ you:")
    print("here you know about what we have in this college")
    print(" In Science,there are")
    print("bachelors in Maths")
    print("chemistry")
    print("physics")
    print("Microbiology")
    print("computer science")
    print("Information technology")
    print("computer application" )
    message = input ("/ you:")
    print("In Arts they are")
    print("Bachelors in commerce")
    print("commerce with computer application")
    print("commerce with IT")             
    print("Business adminstrastion")
    print("E-commerce")
    print("commerce with Banking")
    message = input("/ you:")
    print("Is that clear for you,what i given to you")
    message = input("/ you:")
    print("ok,then you want to know about else...")
    message = input("/ you:")
    print("Thats ok")
    message = input ("/ you:")
    print("Thank you")
    print("Bye!,have a nice day")
else:
    print("Bye!")